using Xunit;

namespace AbpMicroservicesGenerator.EntityFrameworkCore;

[CollectionDefinition(AbpMicroservicesGeneratorTestConsts.CollectionDefinitionName)]
public class AbpMicroservicesGeneratorEntityFrameworkCoreCollection : ICollectionFixture<AbpMicroservicesGeneratorEntityFrameworkCoreFixture>
{

}
