using AbpMicroservicesGenerator.EntityFrameworkCore;
using Xunit;

namespace AbpMicroservicesGenerator.EntityFrameworkCore;

public class AbpMicroservicesGeneratorEntityFrameworkCoreCollectionFixtureBase : ICollectionFixture<AbpMicroservicesGeneratorEntityFrameworkCoreFixture>
{

}
