using Volo.Abp;

namespace AbpMicroservicesGenerator.EntityFrameworkCore;

public abstract class AbpMicroservicesGeneratorEntityFrameworkCoreTestBase : AbpMicroservicesGeneratorTestBase<AbpMicroservicesGeneratorEntityFrameworkCoreTestModule>
{

}
