using Xunit;

namespace AbpSolutionGenerator.EntityFrameworkCore;

[CollectionDefinition(AbpSolutionGeneratorTestConsts.CollectionDefinitionName)]
public class AbpSolutionGeneratorEntityFrameworkCoreCollection : ICollectionFixture<AbpSolutionGeneratorEntityFrameworkCoreFixture>
{

}
