using AbpSolutionGenerator.EntityFrameworkCore;
using Xunit;

namespace AbpSolutionGenerator.EntityFrameworkCore;

public class AbpSolutionGeneratorEntityFrameworkCoreCollectionFixtureBase : ICollectionFixture<AbpSolutionGeneratorEntityFrameworkCoreFixture>
{

}
